services:
  traefik:
    image: traefik:v3.3.3 # 使用Traefik v3.3.3版本的镜像
    container_name: traefik # 设置容器名称为"traefik"，便于识别和管理
    restart: always # 容器重启策略为always，确保Traefik高可用
    ports:
      - "80:80" # 将容器的80端口映射到主机的80端口（HTTP）
      - "443:443" # 将容器的443端口映射到主机的443端口（HTTPS）
    command:
      # 全局配置
      - --global.checknewversion=false # 禁用自动检查新版本功能，避免不必要的网络请求
      - --global.sendanonymoususage=false # 禁用匿名使用数据的发送，保护隐私

      # 日志配置
      - --log.level=ERROR # 设置日志级别为ERROR，仅记录错误信息，减少日志噪音

      # API配置
      - --api=false # 禁用Traefik的API功能，防止未经授权的访问
      - --api.dashboard=false # 禁用API仪表板，进一步减少攻击面
      - --api.insecure=false # 禁用API的不安全模式，确保API不直接暴露
      - --api.debug=false # 禁用API的调试模式，减少资源消耗和安全风险

      # 入口点配置
      - --entrypoints.web.address=:80 # 定义HTTP入口点，监听80端口
      - --entrypoints.websecure.address=:443 # 定义HTTPS入口点，监听443端口

      # 自动HTTP->HTTPS跳转
      - --entrypoints.web.http.redirections.entrypoint.to=websecure # 将HTTP流量重定向到HTTPS入口点
      - --entrypoints.web.http.redirections.entrypoint.scheme=https # 指定重定向的目标协议为HTTPS

      # Docker提供者
      - --providers.docker=true # 启用Docker提供者，允许Traefik自动发现Docker容器上的服务
      - --providers.docker.exposedbydefault=false # 禁止自动暴露所有容器，只有显式配置Traefik标签的容器才会被管理
      - --providers.docker.endpoint=unix:///var/run/docker.sock # 通过Unix套接字与Docker守护进程通信

      # 文件提供者（动态配置）
      - --providers.file.filename=/dynamic.yml # 启用文件提供者，从/dynamic.yml加载动态配置（如路由器、服务、中间件）

      # 证书解析器：Cloudflare
      - --certificatesresolvers.cloudflare.acme.storage=/acme.json # 指定ACME证书存储文件
      - --certificatesresolvers.cloudflare.acme.caserver=https://acme-v02.api.letsencrypt.org/directory # 指定Let's Encrypt的ACME服务器
      - --certificatesresolvers.cloudflare.acme.keytype=EC256 # 使用ECDSA 256位密钥生成证书，安全性高
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare # 使用Cloudflare的DNS-01挑战来验证域名所有权
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53 # 指定DNS解析器为1.1.1.1和8.8.8.8
      - --certificatesresolvers.cloudflare.acme.dnschallenge.delaybeforecheck=60 # 在检查DNS记录前等待60秒，确保记录传播

    env_file:
      - ./data/config.env # 从config.env文件加载环境变量，如Cloudflare API密钥

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # 挂载Docker套接字（只读），允许Traefik与Docker通信
      - ./data/acme.json:/acme.json # 挂载ACME证书文件，用于存储Let's Encrypt证书
      - ./data/dynamic.yml:/dynamic.yml:ro # 挂载动态配置文件（只读），用于Traefik的动态配置

    networks:
      - traefik_network # 将Traefik连接到外部网络traefik_network，以便与用户服务通信

networks:
  traefik_network:
    external: true # 使用外部网络traefik_network（需预先创建）
